version: "3.8"

services:
  go:
    restart: always
    container_name: ${APP_NAME}-go
    ports:
      - "80:${APP_PORT:-8080}"
    build:
      context: .
    depends_on:
      - db
    volumes:
      - .:/app
  
  db:
    image: postgres:14.1-alpine
    container_name: ${APP_NAME}-postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes: 
      - ./db/data:/var/lib/postgresql/data
volumes:
  db:
    driver: local