version: "3.8"

services:
  go:
    restart: always
    container_name: ${APP_NAME}-go
    ports:
      - "80:${APP_PORT:-8080}"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "go mod download &&
             go build -o ./cmd/link_shortener/main &&
             ./cmd/link_shortener/main"
  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes: 
      - ./db/data:/var/lib/postgresql/data
volumes:
  db:
    driver: local